theme: jekyll-theme-slate
repository: nextcloud/cookbook
exclude:
    - "Makefile"
    - Makefile.local
    - .gitignore
    - "vendor/"
    - Gemfile
    - Gemfile.lock
# plugins:
#     - jekyll-spaceship
markdown: kramdown
kramdown:
    input: GFM
