
name: Run test suite on code base
author: Christian Wolf <github@christianwolf.email>
description: <
    This is a github action to test the cookbook Nextcloud app.

inputs:
    phpVersion:
        description: The PHP version to use for the tests
        required: false
        default: '8.0'
    db:
        description: The db type to use
        required: true
    server:
        description: The http server to use for integration testing (apache, nginx)
        required: true
    coreVersion:
        description: The version of the NC server core to test against.
        required: true
    installUntested:
        description: The test may fail
        required: false
        default: "false"
    runCodeChecker:
        description: Setting to true or false to decide if the code checker should run
        required: false
        default: "true"

runs:
    using: 'composite'
    steps:
        - name: Prepare folder for installation
          shell: bash
          run: mkdir -p vendor
        - name: Run all tests
          shell: bash
          id: tests
          run: >-
            if [ "${{inputs.db}}" = 'pgsql' ]; then PARAM=''; else PARAM='--use-db-dump'; fi &&
            if [ "${{ inputs.installUntested }}" = 'true' ]; then PARAM="$PARAM --install-untested"; fi &&
            if [ "${{ inputs.runCodeChecker }}" = 'true' ]; then PARAM="$PARAM --run-code-checker"; fi &&
            cd .github/actions/run-tests &&
            ./run-locally.py
            $PARAM
            --pull
            --create-images
            --input-db ${{ inputs.db }}
            --http-server ${{ inputs.server }}
            --php-version ${{ inputs.phpVersion }}
            --create-fixture default ${{ inputs.coreVersion }}
            --activate-fixture default
            --run-unit-tests
            --run-integration-tests
            --run-migration-tests
            --extract-code-coverage
            --keep-code-coverage
            --install-composer-deps;
            echo "test_result=$?" >> $GITHUB_ENV
        
        - name: Export the annotations of unit tests to github
          shell: bash
          run: >-
            if [ -r .github/actions/run-tests/volumes/coverage/teamcity.log ]; then
            python .github/actions/run-tests/extract-annotations.py .github/actions/run-tests/volumes/coverage/teamcity.log ;
            fi
        - name: Export the annotations of integration tests to github
          shell: bash
          run: >-
            if [ -r .github/actions/run-tests/volumes/coverage/teamcity.integration.log ]; then
            python .github/actions/run-tests/extract-annotations.py .github/actions/run-tests/volumes/coverage/teamcity.integration.log ;
            fi
        - name: Export the annotations of migration tests to github
          shell: bash
          run: >-
            if [ -r .github/actions/run-tests/volumes/coverage/teamcity.migration.log ]; then
            python .github/actions/run-tests/extract-annotations.py .github/actions/run-tests/volumes/coverage/teamcity.migration.log ;
            fi
        
