
name: Build images nightly for unit testing
on:
    workflow_dispatch:
    schedule:
        - cron: "30 2 * * *"

jobs:
    push:
        name: Build and push the latest test images
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                phpVersion:
                    - "7.4"
                    - "7.3"
                    - "8.0"
                    - "8.1"
                    # - "8"
        steps:
            - name: Check if secret is known
              shell: bash
              id: check
              run: |
                echo "::set-output name=skip::false"
                if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
                    echo "::set-output name=skip::true"
                fi
                if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
                    echo "::set-output name=skip::true"
                fi
            
            - name: Checkout the app
              uses: actions/checkout@v2
              if: ${{ steps.check.outputs.skip == 'false' }}
            - name: Make sure the appinfo is built
              shell: bash
              run: make appinfo/info.xml
              if: ${{ steps.check.outputs.skip == 'false' }}
              
            - name: Log into docker regestry as user
              shell: bash
              run: >-
                echo "${{ secrets.DOCKER_HUB_TOKEN }}" 
                | docker login 
                --username ${{ secrets.DOCKER_HUB_USERNAME }} 
                --password-stdin &&

            - name: Build and push the image
              shell: bash
              run: >-
                cd .github/actions/run-tests &&
                export COMPOSE_DOCKER_CLI_BUILD=1 &&
                ./run-locally.py
                --pull
                --create-images
                --push-images
                --php-version ${{ matrix.phpVersion }}
              if: ${{ steps.check.outputs.skip == 'false' }}
